
```{r setup}
library(ggplot2)
library(MOFA2)

```


```{r}
model <- load_model("../../data/MOFA/protein_selected_drug.hdf5")

```
```{r}
p <- plot_variance_explained(model, x="factor", y="view", groups = "group_0")
p + ggtitle("MOFA factors with explained variation") + theme(axis.text.x = element_text(color="black", angle=40, vjust=1, hjust=1), text=element_text(family="Helvetica"), plot.title = element_text(family="Helvetica", size=18)) + theme(strip.text = element_blank())
```


```{r fig.height=8}
plot_data_scatter(model,
  view = "drug",         # view of interest
  factor = 2,             # factor of interest
  features = 4,           # number of features to plot (they are selected by loading)
  add_lm = TRUE,          # add linear regression
)
```

```{r}
df = as.data.frame(cbind(model@data$drug, model@expectations$Z$group_0[, "Factor2"]), row.names = rownames(model@data$drug), col.names = c("IC50", "Factor2"), stringsAsFactors=F)
```


```{r}
plot_data_heatmap(model,
  view = "drug",         # view of interest
  factor = 2,             # factor of interest
  features = 20,          # number of features to plot (they are selected by loading)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = FALSE, cluster_cols = FALSE,
  show_rownames = TRUE, show_colnames = FALSE
)
```

```{r}
head(model@expectations$W$drug[order(-abs(model@expectations$W$drug[,"Factor2"])),], 30)
write.table(model@expectations$W$drug[order(-abs(model@expectations$W$drug[,"Factor2"])),], "../../data/MOFA/mofa_drugs.csv", sep = ",")
```


```{r}
head(model@expectations$W$protein[order(-abs(model@expectations$W$protein[,"Factor2"])),], 20)
```

```{r fig.height=6}
p = plot_weights(model,
  view = "protein",
  factor = 2,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + ggtitle("MOFA factor 2 top proteins") + theme(text=element_text(family="Helvetica"), plot.title = element_text(family="Helvetica", size=18))
ggsave("../../plots/Fig4S-E_MOFA2.pdf", dpi=500)
```

```{r fig.height=6}
p = plot_weights(model,
  view = "protein",
  factor = 3,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + theme(text=element_text(family="Helvetica"))
```