```{r setup}
library(limma)
library(EnhancedVolcano)
```

```{r}
wes = read.table("../../data/genomic/WES_variants_processed.csv.gz", stringsAsFactors = F, sep = ",", header = T, check.names = F)
protein = read.table("../../data/protein/protein_de_processed_rep.csv.gz", stringsAsFactors = F, sep = ",", header = T, row.names = 1, check.names = F)
meta = read.csv2("../../data/E0022_P06_final_sample_map_no_control.txt", sep = "\t", stringsAsFactors = F, check.names = F)
protein = protein[, colnames(protein) %in% meta$Automatic_MS_filename]
```

```{r}
gene = "PHF6"
cell_lines_wt = wes[wes[gene]==0, "Cell_line"]
cell_lines_mut = wes[wes[gene]>0,"Cell_line"]

ms_wt = meta[meta$Cell_line %in% cell_lines_wt, "Automatic_MS_filename"]
ms_mut = meta[meta$Cell_line %in% cell_lines_mut, "Automatic_MS_filename"]

protein_wt = protein[,colnames(protein) %in% ms_wt]
protein_mut = protein[,colnames(protein) %in% ms_mut]

```

```{r fig.height=7, fig.width=9}
mutant = as.numeric(colnames(protein) %in% ms_mut)
design <- model.matrix(~1 + mutant)

fit <- lmFit(protein, design)
fit <- eBayes(fit)
protein_res = topTable(fit, coef=ncol(design), number = nrow(protein))
EnhancedVolcano(protein_res,
    lab = rownames(protein_res),
    title = paste0("WT vs MUT (Protein Replicates) - ", gene),
    subtitle = 'Missing - exclude',
    # titleLabSize = 14,
    # subtitleLabSize = 10,
    # captionLabSize = 10,
    # axisLabSize = 12,
    legendVisible = F,
    x = 'logFC',
    y = 'adj.P.Val',
    labSize=5,
    FCcutoff=0.5,
    pCutoff=1e-2)
```