
```{r setup}
library(ggplot2)
library(MOFA2)

```


```{r}
model.growth_corrected <- load_model("../../data/MOFA/protein_selected_drug_growth_corrected.hdf5")

```
```{r}
p <- plot_variance_explained(model.growth_corrected, x="factor", y="view")
#p + theme(axis.text.x = element_text(color="black", angle=40, vjust=1, hjust=1, family="Helvetica"))
p + theme(axis.text.x = element_text(color="black", angle=40, vjust=1, hjust=1), text=element_text(family="Helvetica"))

```


```{r fig.height=8}
plot_data_scatter(model.growth_corrected,
  view = "drug",         # view of interest
  factor = 3,             # factor of interest
  features = 4,           # number of features to plot (they are selected by loading)
  add_lm = TRUE,          # add linear regression
)
```

```{r}
df = as.data.frame(cbind(model.growth_corrected@data$drug, model.growth_corrected@expectations$Z$group_0[, "Factor2"]), row.names = rownames(model.growth_corrected@data$drug), col.names = c("IC50", "Factor2"), stringsAsFactors=F)
```


```{r}
plot_data_heatmap(model.growth_corrected,
  view = "drug",         # view of interest
  factor = 2,             # factor of interest
  features = 20,          # number of features to plot (they are selected by loading)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = FALSE, cluster_cols = FALSE,
  show_rownames = TRUE, show_colnames = FALSE
)
```

```{r}
head(model.growth_corrected@expectations$W$drug[order(-abs(model.growth_corrected@expectations$W$drug[,"Factor2"])),], 30)
write.table(model.growth_corrected@expectations$W$drug[order(-abs(model.growth_corrected@expectations$W$drug[,"Factor2"])),], "../../data/MOFA/mofa_drugs.csv", sep = ",")
```


```{r}
head(model.growth_corrected@expectations$W$protein[order(-abs(model.growth_corrected@expectations$W$protein[,"Factor2"])),], 20)
```
```{r fig.height=6}
p = plot_weights(model.growth_corrected,
  view = "protein",
  factor = 2,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + theme(text=element_text(family="Helvetica"))
```

```{r fig.height=6}
p = plot_weights(model.growth_corrected,
  view = "protein",
  factor = 3,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + theme(text=element_text(family="Helvetica"))
```